### ISSUE TITLE
Typescript build errors after updating to v1.1.1

### ISSUE THREAD

**Issue by hardmaster92** [googlemaps/js-markerclustererplus#195]
I've been using the marker cluster library for months within a Typescript (Angular) project. Everything worked fine until I updated yesterday to v1.1.1. Now when I try to build the project I get various type errors during compilation:
```
Error: node_modules/@googlemaps/markerclustererplus/dist/cluster-icon.d.ts:16:23 - error TS2688: Cannot find type definition file for 'google.maps'.
16 /// <reference types="google.maps" />
                         ~~~~~~~~~~~


Error: node_modules/@googlemaps/markerclustererplus/dist/cluster-icon.d.ts:178:23 - error TS2503: Cannot find namespace 'google'.

178     setCenter(center: google.maps.LatLng): void;
                          ~~~~~~


Error: node_modules/@googlemaps/markerclustererplus/dist/cluster.d.ts:103:37 - error TS2503: Cannot find namespace 'google'.

103     isMarkerInClusterBounds(marker: google.maps.Marker): boolean;
                                        ~~~~~~


Error: node_modules/@googlemaps/markerclustererplus/dist/cluster.d.ts:16:23 - error TS2688: Cannot find type definition file for 'google.maps'.     

16 /// <reference types="google.maps" />
```

When i revert back to v1.1.0 these errors disappear. If you need further information about my packages, I'm using `@types/googlemaps` (v3.43.3). As for the google maps API - I lazy load it using this link `https://maps.googleapis.com/maps/api/js` which is supposed to always return the latest version of the API.

**Comment by jpoehnelt** [comment]
v1.1.1 switched to the [@types/google.maps](https://www.npmjs.com/package/@types/google.maps) which is [the officially generated types for Google Maps Platform JavaScript API](https://developers.google.com/maps/documentation/javascript/using-typescript). 

![Screenshot 2021-05-04 9 10 31 AM](https://user-images.githubusercontent.com/3392975/117025972-99d89500-acb8-11eb-8b46-f70c4e5b839e.png)

You can install that package but might need to set the compiler option `skipLibCheck` to `true`. https://www.typescriptlang.org/tsconfig#skipLibCheck

**Comment by hardmaster92** [comment]
@jpoehnelt  thanks for the help! Switching to `@types/google.maps` fixed the issues.
